name: Test solutions

on:
  push:
    branches:
      - master

jobs:
  tests:
    environment: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - run: go version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download -x

      - name: Run lint
        run: make lint

      - name: Run Tests
        run: make test
